import type { AnswerMap, Question, QuestionnaireSchema } from "./types";

const yesNo = [
  { label: "Sim", value: "sim" },
  { label: "Não", value: "nao" },
];

const yesNoUnknown = [
  { label: "Sim", value: "sim" },
  { label: "Não", value: "nao" },
  { label: "Não sabe", value: "nao_sabe" },
];

const documentStatus = [
  { label: "Possui", value: "possui" },
  { label: "Documento extraviado", value: "extraviado" },
  { label: "Nunca possuiu", value: "nunca_possuiu" },
];

const institutional = (
  key: string,
  sectionKey: string,
  label: string,
  questionKey: string,
): Question => ({
  key,
  label,
  type: "radio",
  sectionKey,
  institutional: true,
  options: yesNoUnknown,
  condition: { questionKey, operator: "not_empty" },
});

export const questionnaire: QuestionnaireSchema = {
  id: "questionario-biopsicossocial",
  title: "Questionário Padronizado para Avaliação Biopsicossocial",
  version: "v2",
  sourceFile: "QuestionarioBioPsicosSocial-v2.pdf",
  sections: [
    {
      key: "informacoes_iniciais",
      title: "1. Informações iniciais",
      questions: [
        {
          key: "nome_registro",
          number: "1.1",
          label: "Nome de registro",
          type: "text",
          sectionKey: "informacoes_iniciais",
          required: true,
          sensitive: true,
        },
        {
          key: "nome_social",
          number: "1.2",
          label: "Nome social",
          type: "text",
          sectionKey: "informacoes_iniciais",
          sensitive: true,
        },
        {
          key: "comunica_portugues",
          number: "1.3",
          label: "Comunica-se em português?",
          type: "radio",
          sectionKey: "informacoes_iniciais",
          required: true,
          options: yesNo,
        },
        {
          key: "linguas_comunicacao",
          number: "1.3.1",
          label: "Qual(is) língua(s) se comunica?",
          type: "text",
          sectionKey: "informacoes_iniciais",
          condition: {
            questionKey: "comunica_portugues",
            operator: "equals",
            value: "nao",
          },
        },
        institutional(
          "interprete_garantido",
          "informacoes_iniciais",
          "Classificação institucional: Foi garantido acesso a intérprete?",
          "linguas_comunicacao",
        ),
        {
          key: "necessita_acessibilidade_entrevista",
          number: "1.4",
          label:
            "Necessita de algum recurso de acessibilidade para a realização da entrevista?",
          type: "radio",
          sectionKey: "informacoes_iniciais",
          options: yesNo,
        },
        {
          key: "recurso_acessibilidade_entrevista",
          number: "1.4.1",
          label: "Qual recurso de acessibilidade?",
          type: "text",
          sectionKey: "informacoes_iniciais",
          condition: {
            questionKey: "necessita_acessibilidade_entrevista",
            operator: "equals",
            value: "sim",
          },
        },
      ],
    },
    {
      key: "informacoes_pessoais",
      title: "2. Informações pessoais",
      questions: [
        {
          key: "nacionalidade",
          number: "2.1",
          label: "Nacionalidade",
          type: "text",
          sectionKey: "informacoes_pessoais",
        },
        {
          key: "brasileiro_tipo",
          number: "2.1.2",
          label: "Caso seja brasileiro(a), indique",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          options: [
            { label: "Nato(a)", value: "nato" },
            { label: "Naturalizado(a)", value: "naturalizado" },
          ],
        },
        {
          key: "cidade_uf_nascimento",
          number: "2.1.3",
          label: "Cidade e UF de nascimento",
          type: "text",
          sectionKey: "informacoes_pessoais",
        },
        {
          key: "tem_deficiencia",
          number: "2.2",
          label: "Você tem alguma deficiência?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "tipo_deficiencia",
          number: "2.2.1",
          label: "Tipo de deficiência",
          type: "checkbox",
          sectionKey: "informacoes_pessoais",
          sensitive: true,
          options: [
            { label: "Física", value: "fisica" },
            { label: "Psicossocial", value: "psicossocial" },
            { label: "Intelectual", value: "intelectual" },
            { label: "Auditiva", value: "auditiva" },
            { label: "Visual", value: "visual" },
          ],
          condition: { questionKey: "tem_deficiencia", operator: "equals", value: "sim" },
        },
        institutional(
          "espacos_adequados_deficiencia",
          "informacoes_pessoais",
          "Classificação institucional: Há espaços adequados para pessoas com deficiência?",
          "tem_deficiencia",
        ),
        {
          key: "mobilidade_reduzida",
          number: "2.3",
          label: "Você tem mobilidade reduzida?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          options: yesNo,
          sensitive: true,
        },
        institutional(
          "espacos_adequados_mobilidade",
          "informacoes_pessoais",
          "Classificação institucional: Há espaços adequados para pessoas com mobilidade reduzida?",
          "mobilidade_reduzida",
        ),
        {
          key: "raca_cor",
          number: "2.4",
          label: "Você se autodeclara como uma pessoa",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          sensitive: true,
          options: [
            { label: "Branca", value: "branca" },
            { label: "Preta", value: "preta" },
            { label: "Parda", value: "parda" },
            { label: "Amarela", value: "amarela" },
            { label: "Indígena", value: "indigena" },
          ],
        },
        {
          key: "acompanhamento_funai",
          number: "2.4.1",
          label: "Você recebe acompanhamento da FUNAI?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          options: yesNo,
          condition: { questionKey: "raca_cor", operator: "equals", value: "indigena" },
        },
        {
          key: "etnia_povo",
          number: "2.4.2",
          label: "Qual etnia/povo a que pertence?",
          type: "text",
          sectionKey: "informacoes_pessoais",
          sensitive: true,
          condition: { questionKey: "raca_cor", operator: "equals", value: "indigena" },
        },
        {
          key: "orientacao_sexual",
          number: "2.6",
          label: "Qual a sua orientação sexual?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          sensitive: true,
          options: [
            { label: "Heterossexual", value: "heterossexual" },
            { label: "Homossexual (Gay ou Lésbica)", value: "homossexual" },
            { label: "Bissexual", value: "bissexual" },
            { label: "Pansexual", value: "pansexual" },
            { label: "Assexual", value: "assexual" },
            { label: "Outro", value: "outro", allowsText: true },
            { label: "Prefere não informar", value: "prefere_nao_informar" },
          ],
        },
        {
          key: "identidade_genero",
          number: "2.7",
          label: "Qual a sua identificação de gênero?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          sensitive: true,
          options: [
            { label: "Homem cisgênero", value: "homem_cis" },
            { label: "Mulher cisgênero", value: "mulher_cis" },
            { label: "Homem trans", value: "homem_trans" },
            { label: "Mulher trans", value: "mulher_trans" },
            { label: "Travesti", value: "travesti" },
            { label: "Intersexo", value: "intersexo" },
            { label: "Não-binário", value: "nao_binario" },
            { label: "Queer", value: "queer" },
            { label: "Outro", value: "outro", allowsText: true },
            { label: "Prefere não informar", value: "prefere_nao_informar" },
          ],
        },
        {
          key: "encaminhamento_pessoais",
          label:
            "Tem interesse em encaminhamentos relativos a atendimento especializado, acessibilidade ou tratamento antidiscriminatório?",
          type: "radio",
          sectionKey: "informacoes_pessoais",
          options: yesNo,
        },
        {
          key: "encaminhamento_pessoais_notas",
          label: "Encaminhamentos",
          type: "textarea",
          sectionKey: "informacoes_pessoais",
          condition: {
            questionKey: "encaminhamento_pessoais",
            operator: "equals",
            value: "sim",
          },
        },
      ],
    },
    {
      key: "processuais_juridicas",
      title: "3. Informações processuais e jurídicas",
      questions: [
        {
          key: "situacao_juridica",
          number: "3.1",
          label: "Situação jurídica",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: [
            { label: "Prisão provisória", value: "prisao_provisoria" },
            { label: "Prisão definitiva", value: "prisao_definitiva" },
          ],
        },
        {
          key: "primeira_prisao",
          number: "3.2",
          label: "É a primeira prisão?",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: yesNo,
        },
        {
          key: "quantas_prisoes",
          number: "3.2.1",
          label: "Quantas prisões?",
          type: "number",
          sectionKey: "processuais_juridicas",
          condition: { questionKey: "primeira_prisao", operator: "equals", value: "nao" },
        },
        {
          key: "defesa_tecnica_constituida",
          number: "3.3",
          label: "Defesa técnica constituída?",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: yesNo,
        },
        {
          key: "tipo_defesa",
          number: "3.3.1",
          label: "Tipo de defesa",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: [
            { label: "Advogado particular", value: "advogado_particular" },
            { label: "Defensor público", value: "defensor_publico" },
          ],
          condition: {
            questionKey: "defesa_tecnica_constituida",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "teve_transferencia_recambiamento",
          number: "3.4",
          label:
            "Você veio de transferência de outra unidade prisional ou recambiamento de outra UF?",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: yesNo,
        },
        {
          key: "precisa_transferencia_recambiamento",
          number: "3.5",
          label: "Você tem interesse e/ou necessidade de transferência ou recambiamento?",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: yesNo,
        },
        {
          key: "motivos_transferencia",
          number: "3.5.1",
          label: "Por quais motivos?",
          type: "checkbox",
          sectionKey: "processuais_juridicas",
          options: [
            { label: "Risco à vida ou à integridade", value: "risco_vida_integridade" },
            { label: "Necessidade de tratamento médico", value: "tratamento_medico" },
            { label: "Proximidade do meio social e familiar", value: "proximidade_familiar" },
            { label: "Atividade laborativa ou educacional", value: "trabalho_educacao" },
            { label: "Outro", value: "outro", allowsText: true },
          ],
          condition: {
            questionKey: "precisa_transferencia_recambiamento",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "encaminhamento_defesa",
          label: "Tem interesse em encaminhamentos relativos à defesa técnica?",
          type: "radio",
          sectionKey: "processuais_juridicas",
          options: yesNo,
        },
        {
          key: "encaminhamento_defesa_notas",
          label: "Encaminhamentos",
          type: "textarea",
          sectionKey: "processuais_juridicas",
          condition: { questionKey: "encaminhamento_defesa", operator: "equals", value: "sim" },
        },
      ],
    },
    {
      key: "documentacao_civil",
      title: "4. Documentação civil",
      questions: [
        ...[
          ["cin_rg", "4.1", "Carteira de Identidade Nacional/Registro Geral (CIN ou RG)"],
          ["cpf", "4.2", "Cadastro de Pessoa Física (CPF)"],
          ["certidao_nascimento", "4.3", "Certidão de nascimento"],
          ["certidao_casamento", "4.4", "Certidão de casamento"],
          ["ctps", "4.5", "Carteira de Trabalho e Previdência Social (CTPS)"],
          ["cnh", "4.6", "Carteira Nacional de Habilitação (CNH)"],
          ["titulo_eleitor", "4.7", "Título de eleitor"],
          ["passaporte", "4.8", "Passaporte"],
          ["alistamento_militar", "4.9", "Certificado de Alistamento Militar"],
        ].flatMap(([key, number, label]) => [
          {
            key: `doc_${key}_status`,
            number,
            label: `Possui ${label}?`,
            type: "radio" as const,
            sectionKey: "documentacao_civil",
            options:
              key === "alistamento_militar"
                ? [...documentStatus, { label: "Isento(a)", value: "isento" }]
                : documentStatus,
          },
          {
            key: `doc_${key}_local`,
            number: `${number}.1`,
            label: "Onde e com quem está?",
            type: "text" as const,
            sectionKey: "documentacao_civil",
            sensitive: true,
            condition: {
              questionKey: `doc_${key}_status`,
              operator: "equals" as const,
              value: "possui",
            },
          },
          institutional(
            `doc_${key}_emissao_garantida`,
            "documentacao_civil",
            `Classificação institucional: foi garantida a emissão de ${label}?`,
            `doc_${key}_status`,
          ),
        ]),
        {
          key: "encaminhamento_documentacao",
          label: "Tem interesse em encaminhamentos relativos à documentação civil?",
          type: "radio",
          sectionKey: "documentacao_civil",
          options: yesNo,
        },
        {
          key: "encaminhamento_documentacao_notas",
          label: "Encaminhamentos",
          type: "textarea",
          sectionKey: "documentacao_civil",
          condition: {
            questionKey: "encaminhamento_documentacao",
            operator: "equals",
            value: "sim",
          },
        },
      ],
    },
    {
      key: "sociofamiliares",
      title: "5. Informações sociofamiliares",
      questions: [
        {
          key: "tem_dependentes",
          number: "5.1",
          label: "Você tem dependentes?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
        },
        {
          key: "quantos_dependentes",
          number: "5.1.1",
          label: "Quantos dependentes?",
          type: "number",
          sectionKey: "sociofamiliares",
          condition: { questionKey: "tem_dependentes", operator: "equals", value: "sim" },
        },
        {
          key: "responsavel_cuidados",
          number: "5.2",
          label:
            "Você é responsável pelo cuidado de crianças, adolescentes, pessoas com deficiência ou idosos?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
        },
        {
          key: "nome_mae",
          number: "5.3",
          label: "Nome da mãe",
          type: "text",
          sectionKey: "sociofamiliares",
          sensitive: true,
        },
        {
          key: "nome_pai",
          number: "5.4",
          label: "Nome do pai",
          type: "text",
          sectionKey: "sociofamiliares",
          sensitive: true,
        },
        {
          key: "possui_filhos",
          number: "5.8",
          label: "Possui filho(s)?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
        },
        {
          key: "quantos_filhos",
          number: "5.8.1",
          label: "Quantos filhos?",
          type: "number",
          sectionKey: "sociofamiliares",
          condition: { questionKey: "possui_filhos", operator: "equals", value: "sim" },
        },
        {
          key: "filhos_no_estabelecimento",
          number: "5.8.8",
          label: "Algum(ns) do(s) filho(s) está no estabelecimento penal?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
          condition: { questionKey: "possui_filhos", operator: "equals", value: "sim" },
        },
        {
          key: "amamentando",
          number: "5.8.8.1",
          label: "Atualmente, está amamentando?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
          sensitive: true,
          condition: {
            questionKey: "filhos_no_estabelecimento",
            operator: "equals",
            value: "sim",
          },
        },
        institutional(
          "espaco_filhos_unidade",
          "sociofamiliares",
          "Classificação institucional: Há espaço adequado para permanência de filhos na unidade?",
          "filhos_no_estabelecimento",
        ),
        {
          key: "situacao_rua",
          number: "5.14",
          label: "Você já esteve em situação de rua?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
          sensitive: true,
        },
        institutional(
          "atencao_situacao_rua",
          "sociofamiliares",
          "Classificação institucional: O estabelecimento ofertou atenção especializada considerando trajetória de rua?",
          "situacao_rua",
        ),
        {
          key: "encaminhamento_familia",
          label:
            "Tem interesse em encaminhamentos relativos à convivência familiar e comunitária?",
          type: "radio",
          sectionKey: "sociofamiliares",
          options: yesNo,
        },
        {
          key: "encaminhamento_familia_notas",
          label: "Encaminhamentos",
          type: "textarea",
          sectionKey: "sociofamiliares",
          condition: { questionKey: "encaminhamento_familia", operator: "equals", value: "sim" },
        },
      ],
    },
    {
      key: "religiao",
      title: "6. Espiritualidade e religião",
      questions: [
        {
          key: "professa_fe",
          number: "6.1",
          label: "Você professa alguma fé ou possui religião?",
          type: "radio",
          sectionKey: "religiao",
          options: yesNo,
        },
        {
          key: "religiao_qual",
          number: "6.1.1",
          label: "Qual?",
          type: "radio",
          sectionKey: "religiao",
          options: [
            { label: "Católica Apostólica Romana", value: "catolica" },
            { label: "Evangélica", value: "evangelica" },
            { label: "Espírita", value: "espirita" },
            { label: "Umbanda, Candomblé e religiões afrobrasileiras", value: "afrobrasileira" },
            { label: "Tradições indígenas", value: "tradicoes_indigenas" },
            { label: "Outras religiosidades", value: "outras" },
            { label: "Não sabe", value: "nao_sabe" },
            { label: "Prefere não informar", value: "prefere_nao_informar" },
          ],
          condition: { questionKey: "professa_fe", operator: "equals", value: "sim" },
        },
        institutional(
          "direito_assistencia_religiosa",
          "religiao",
          "Classificação institucional: Foi garantido o direito de professar a própria fé?",
          "professa_fe",
        ),
        {
          key: "encaminhamento_religiao",
          label: "Tem interesse em encaminhamentos relativos à assistência religiosa?",
          type: "radio",
          sectionKey: "religiao",
          options: yesNo,
        },
      ],
    },
    {
      key: "trabalho",
      title: "7. Trabalho",
      questions: [
        {
          key: "trabalhou_antes_prisao",
          number: "7.1",
          label: "Você já trabalhou antes da sua prisão?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
        },
        {
          key: "trabalho_atual_unidade",
          number: "7.2",
          label: "Atualmente, realiza atividade laboral no estabelecimento penal?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
        },
        institutional(
          "oportunidade_trabalho_oferecida",
          "trabalho",
          "Classificação institucional: Foi oferecida oportunidade de trabalho a esta pessoa?",
          "trabalho_atual_unidade",
        ),
        {
          key: "trabalho_remunerado",
          number: "7.2.2",
          label: "É remunerado?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
          condition: { questionKey: "trabalho_atual_unidade", operator: "equals", value: "sim" },
        },
        {
          key: "curso_profissionalizante_prisao",
          number: "7.4",
          label: "Durante o tempo de prisão, já realizou algum curso profissionalizante?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
        },
        {
          key: "trabalhava_outra_unidade",
          number: "7.10",
          label: "Estava trabalhando na outra unidade prisional?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
          condition: {
            questionKey: "teve_transferencia_recambiamento",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "encaminhamento_trabalho",
          label: "Tem interesse em encaminhamentos relativos à inserção sociolaboral?",
          type: "radio",
          sectionKey: "trabalho",
          options: yesNo,
        },
      ],
    },
    {
      key: "assistencia_material",
      title: "8. Assistência material",
      questions: [
        {
          key: "acesso_kit_basico",
          number: "8.1",
          label: "Teve acesso ao kit básico de assistência material?",
          type: "radio",
          sectionKey: "assistencia_material",
          options: yesNo,
        },
        institutional(
          "kit_reposto_regularmente",
          "assistencia_material",
          "Classificação institucional: O kit é reposto regularmente?",
          "acesso_kit_basico",
        ),
        {
          key: "beneficio_socioassistencial",
          number: "8.3",
          label: "Atualmente recebe algum benefício socioassistencial?",
          type: "radio",
          sectionKey: "assistencia_material",
          options: yesNoUnknown,
        },
        {
          key: "kit_lgbti",
          number: "8.4",
          label:
            "Recebeu kit básico e insumos complementares conforme identidade de gênero?",
          type: "radio",
          sectionKey: "assistencia_material",
          options: yesNo,
          condition: {
            questionKey: "identidade_genero",
            operator: "includes",
            value: ["mulher_trans", "travesti", "intersexo", "nao_binario", "queer"],
          },
        },
        {
          key: "encaminhamento_material",
          label: "Tem interesse em encaminhamentos relativos à assistência material?",
          type: "radio",
          sectionKey: "assistencia_material",
          options: yesNo,
        },
      ],
    },
    {
      key: "educacao_cultura_esportes",
      title: "9. Educação, cultura e esportes",
      questions: [
        {
          key: "nivel_ensino",
          number: "9.1",
          label: "Qual seu nível de ensino?",
          type: "select",
          sectionKey: "educacao_cultura_esportes",
          options: [
            { label: "Em processo de alfabetização", value: "alfabetizacao" },
            { label: "Ensino fundamental incompleto", value: "fundamental_incompleto" },
            { label: "Ensino fundamental completo", value: "fundamental_completo" },
            { label: "Ensino médio incompleto", value: "medio_incompleto" },
            { label: "Ensino médio completo", value: "medio_completo" },
            { label: "Ensino superior incompleto", value: "superior_incompleto" },
            { label: "Ensino superior completo", value: "superior_completo" },
            { label: "Especialização/aprimoramento", value: "especializacao" },
            { label: "Mestrado", value: "mestrado" },
            { label: "Doutorado", value: "doutorado" },
          ],
        },
        {
          key: "estuda_atualmente",
          number: "9.2",
          label: "Estuda atualmente?",
          type: "radio",
          sectionKey: "educacao_cultura_esportes",
          options: yesNo,
        },
        institutional(
          "atividade_educacao_ofertada",
          "educacao_cultura_esportes",
          "Classificação institucional: Foi ofertada atividade de educação escolar?",
          "estuda_atualmente",
        ),
        {
          key: "interesse_enem_encceja",
          number: "9.3",
          label: "Tem interesse de fazer o ENCCEJA e/ou ENEM?",
          type: "radio",
          sectionKey: "educacao_cultura_esportes",
          options: yesNo,
        },
        {
          key: "estudava_outra_unidade",
          number: "9.8",
          label: "Estava estudando na outra unidade prisional?",
          type: "radio",
          sectionKey: "educacao_cultura_esportes",
          options: yesNo,
          condition: {
            questionKey: "teve_transferencia_recambiamento",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "encaminhamento_educacao",
          label: "Tem interesse em encaminhamentos relativos à educação, cultura e esporte?",
          type: "radio",
          sectionKey: "educacao_cultura_esportes",
          options: yesNo,
        },
      ],
    },
    {
      key: "saude",
      title: "10. Saúde",
      questions: [
        {
          key: "acesso_equipe_saude",
          number: "10.1",
          label: "Possui acesso à equipe de saúde da unidade?",
          type: "radio",
          sectionKey: "saude",
          options: yesNo,
          sensitive: true,
        },
        institutional(
          "acesso_saude_garantido",
          "saude",
          "Classificação institucional: Foi garantido acesso à equipe de saúde?",
          "acesso_equipe_saude",
        ),
        {
          key: "doenca_cronica",
          number: "10.2",
          label: "Possui alguma doença crônica?",
          type: "radio",
          sectionKey: "saude",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "doenca_cronica_qual",
          number: "10.2.1",
          label: "Qual(is)?",
          type: "text",
          sectionKey: "saude",
          sensitive: true,
          condition: { questionKey: "doenca_cronica", operator: "equals", value: "sim" },
        },
        {
          key: "medicacao_continua",
          number: "10.3",
          label: "Faz uso contínuo de alguma medicação?",
          type: "radio",
          sectionKey: "saude",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "gestante",
          number: "10.21",
          label: "Está gestante?",
          type: "radio",
          sectionKey: "saude",
          options: yesNoUnknown,
          sensitive: true,
          condition: {
            questionKey: "identidade_genero",
            operator: "includes",
            value: ["mulher_cis", "homem_trans", "nao_binario", "queer"],
          },
        },
        {
          key: "semanas_gestacao",
          number: "10.21.1",
          label: "Quantas semanas?",
          type: "text",
          sectionKey: "saude",
          sensitive: true,
          condition: { questionKey: "gestante", operator: "equals", value: "sim" },
        },
        institutional(
          "atendimento_gestacao",
          "saude",
          "Classificação institucional: Foi ofertado atendimento especializado para a gestação?",
          "gestante",
        ),
        {
          key: "filho_acompanhado_saude",
          number: "10.22",
          label: "Seu/sua filho(a) está sendo acompanhado(a) por equipe de saúde na unidade?",
          type: "radio",
          sectionKey: "saude",
          options: yesNo,
          condition: {
            questionKey: "filhos_no_estabelecimento",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "encaminhamento_saude",
          label: "Tem interesse em encaminhamentos relativos à saúde?",
          type: "radio",
          sectionKey: "saude",
          options: yesNo,
        },
      ],
    },
    {
      key: "saude_mental",
      title: "11. Saúde mental",
      questions: [
        {
          key: "diagnostico_saude_mental",
          number: "11.1",
          label:
            "Possui diagnóstico ou indícios de transtorno mental ou deficiência psicossocial?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNoUnknown,
          sensitive: true,
        },
        {
          key: "diagnostico_saude_mental_qual",
          number: "11.1.1",
          label: "Qual(is)?",
          type: "text",
          sectionKey: "saude_mental",
          sensitive: true,
          condition: {
            questionKey: "diagnostico_saude_mental",
            operator: "equals",
            value: "sim",
          },
        },
        {
          key: "acompanhamento_psiquiatra",
          number: "11.3",
          label: "Está em acompanhamento com médico/a psiquiatra?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "acompanhamento_psicologo",
          number: "11.4",
          label: "Está em acompanhamento com psicólogo/a?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
          sensitive: true,
        },
        institutional(
          "servico_saude_mental_ofertado",
          "saude_mental",
          "Classificação institucional: Foi ofertado serviço especializado para saúde mental ou redução de danos?",
          "acompanhamento_psicologo",
        ),
        {
          key: "uso_abusivo_substancias",
          number: "11.6",
          label: "Considera que faz uso abusivo de álcool, tabaco e/ou outras drogas?",
          type: "radio",
          sectionKey: "saude_mental",
          options: [
            ...yesNo,
            { label: "Prefere não informar", value: "prefere_nao_informar" },
          ],
          sensitive: true,
        },
        {
          key: "ideacao_suicida",
          number: "11.10",
          label: "Já teve ideação suicida?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "tentativa_suicidio",
          number: "11.11",
          label: "Já tentou suicídio?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "automutilacao",
          number: "11.12",
          label: "Já praticou automutilação?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
          sensitive: true,
        },
        {
          key: "encaminhamento_saude_mental",
          label: "Tem interesse em encaminhamentos relativos à saúde mental?",
          type: "radio",
          sectionKey: "saude_mental",
          options: yesNo,
        },
      ],
    },
  ],
};

export const allQuestions = questionnaire.sections.flatMap((section) => section.questions);

export const questionByKey = new Map(allQuestions.map((question) => [question.key, question]));

export function isLgbtiAnswer(answers: AnswerMap) {
  const orientation = answers.orientacao_sexual;
  const gender = answers.identidade_genero;

  return (
    ["homossexual", "bissexual", "pansexual", "assexual", "outro"].includes(
      String(orientation),
    ) ||
    ["homem_trans", "mulher_trans", "travesti", "intersexo", "nao_binario", "queer"].includes(
      String(gender),
    )
  );
}
